version: '3.0'

services:
  postgres:
    container_name: educa7
    image: postgres:12
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB:educa7

    ports:
      - '5432:5432'
    volumes:
      - ./data:/data/postgres
